### ISSUE TITLE
Checkpoint loading issues

### ISSUE THREAD

**Issue by HidyHan** [fauxneticien/E2E-language-diarization-transfer#2]
There are two issues:

- For both the BLSTM and XSA checkpoints, the parameter shape suggests they were trained with 2 labels. However, the original paper suggests silence should be its own category, so there should be at least 3 labels. The example txt file Hexin provided only contains 0 and 1. Right now, we use 0 to denote silence, 1 Hindi and 2 for English. Were the models trained only on the speech portions? Should we discard all the 0 labels? 

- When I load the XSA checkpoint, I encountered the error that some parameters are missing. `python train_xsa_e2e.py --savedir "/home/hidyhan" --train "./train.txt" --test "./test.txt" --seed 42 --device 0 --batch 64 --epochs 30 --dim 23 --lang 2 --model my_xsa_model --lr 0.0001 --maxlength 666 --lambda_p 0.5 --testonly True --model_ckpt "Transformer_89.0304_5.4848.ckpt"
Current device: cuda:0
Traceback (most recent call last):
  File "train_xsa_e2e.py", line 177, in <module>
    main()
  File "train_xsa_e2e.py", line 123, in main
    model.load_state_dict(torch.load(args.model_ckpt, map_location='cuda:0'))
  File "/home/hidyhan/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for X_Transformer_E2E_LID:
	Missing key(s) in state_dict: "fc5.weight", "fc5.bias", "bn5.running_mean", "bn5.running_var", "fc6.weight", "fc6.bias", "bn6.running_mean", "bn6.running_var", "fc7.weight", "fc7.bias". 
	Unexpected key(s) in state_dict: "fc1.weight", "fc1.bias", "bn_fc1.running_mean", "bn_fc1.running_var", "bn_fc1.num_batches_tracked", "fc2.weight", "fc2.bias", "bn_fc2.running_mean", "bn_fc2.running_var", "bn_fc2.num_batches_tracked", "fc3.weight", "fc3.bias", "pos_encoding.pe". `
(need to comment out strict=False param on line 123 in train_xsa_e2e.py to reproduce the issue)

I also added the testing commands in README.

**Comment by Lhx94As** [comment]
It seems that you are using the code forked from my Github but not the one I sent to you. I renamed some of the layers so the errors are "missing keys". You may figure this out by replacing your model.py with the one I sent to you.
